import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

export type StatementData = {
  guardianEmail: string;
  schoolName: string;
  termLabel: string;       // e.g. "Autumn 2026"
  termStart: string;       // ISO date
  termEnd: string;         // ISO date
  transactions: Array<{
    date: string;
    requestTitle: string;
    studentName: string;
    amountPence: number;
  }>;
  totalPence: number;
};

const styles = StyleSheet.create({
  page: { fontSize: 10, fontFamily: "Helvetica", padding: 48, color: "#111" },
  header: { marginBottom: 24 },
  title: { fontSize: 16, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#555", marginBottom: 2 },
  notice: { marginTop: 16, padding: 10, backgroundColor: "#f0f9ff", borderRadius: 4 },
  noticeText: { fontSize: 9, color: "#1e40af" },
  table: { marginTop: 20 },
  thead: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingBottom: 6, marginBottom: 4 },
  th: { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#6b7280", textTransform: "uppercase" },
  row: { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 0.5, borderBottomColor: "#f3f4f6" },
  td: { fontSize: 9, color: "#374151" },
  total: { flexDirection: "row", justifyContent: "flex-end", marginTop: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#e5e7eb" },
  totalLabel: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111" },
  footer: { marginTop: 32, fontSize: 8, color: "#9ca3af" },
});

function fmt(pence: number) {
  return `£${(pence / 100).toFixed(2)}`;
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

function StatementDoc({ data }: { data: StatementData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Childcare Costs Statement</Text>
          <Text style={styles.subtitle}>{data.schoolName}</Text>
          <Text style={styles.subtitle}>{data.termLabel} · {fmtDate(data.termStart)} – {fmtDate(data.termEnd)}</Text>
          <Text style={styles.subtitle}>Parent / guardian: {data.guardianEmail}</Text>

          <View style={styles.notice}>
            <Text style={styles.noticeText}>
              This statement confirms payments made for childcare and wraparound activities during the above term.
              It may be used as evidence of childcare costs when claiming Universal Credit childcare element or Tax-Free Childcare.
              Retain this document for your records.
            </Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.thead}>
            <Text style={[styles.th, { flex: 2 }]}>Date</Text>
            <Text style={[styles.th, { flex: 4 }]}>Activity / request</Text>
            <Text style={[styles.th, { flex: 2 }]}>Child</Text>
            <Text style={[styles.th, { flex: 1.5, textAlign: "right" }]}>Amount</Text>
          </View>
          {data.transactions.map((tx, i) => (
            <View key={i} style={styles.row}>
              <Text style={[styles.td, { flex: 2 }]}>{fmtDate(tx.date)}</Text>
              <Text style={[styles.td, { flex: 4 }]}>{tx.requestTitle}</Text>
              <Text style={[styles.td, { flex: 2 }]}>{tx.studentName}</Text>
              <Text style={[styles.td, { flex: 1.5, textAlign: "right", fontFamily: "Helvetica-Bold" }]}>{fmt(tx.amountPence)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.total}>
          <Text style={styles.totalLabel}>Total paid this term: {fmt(data.totalPence)}</Text>
        </View>

        <View style={styles.footer}>
          <Text>Generated by School2Pay · {new Date().toLocaleDateString("en-GB")} · This document is a payment record only and does not constitute tax advice.</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generateChildcareStatementPdf(data: StatementData): Promise<Buffer> {
  return renderToBuffer(<StatementDoc data={data} />);
}
